export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_LOADING = 'LOGOUT_LOADING';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const RESET_LOADING = 'RESET_LOADING';
export const RESET_SUCCESS = 'RESET_SUCCESS';
export const RESET_FAILURE = 'RESET_FAILURE';


export const FORGOT_PASSWORD_LOADING = 'FORGOT_PASSWORD_LOADING';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';


export const FORGOT_PASSWORD_LOADING2 = 'FORGOT_PASSWORD_LOADING2';
export const FORGOT_PASSWORD_SUCCESS2 = 'FORGOT_PASSWORD_SUCCESS2';
export const FORGOT_PASSWORD_FAILURE2 = 'FORGOT_PASSWORD_FAILURE2';


export const VERIFY_EMAIL_LOADING = ' VERIFY_EMAIL_LOADING';
export const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_FAILURE = 'VERIFY_EMAIL_FAILURE';

// RESEND OTP
export const RESEND_OTP_LOADING = ' RESEND_OTP_LOADING';
export const RESEND_OTP_SUCCESS = 'RESEND_OTP_SUCCESS';
export const RESEND_OTP_FAILURE = 'RESEND_OTP_FAILURE';

// PROFILE
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const PROFILE_FAILURE = 'PROFILE_FAILURE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const GET_SINGLE_PROFILE = 'GET_SINGLE_PROFILE';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';

// INTERESTS
export const INTEREST_LOADING = ' INTEREST_LOADING';
export const GET_INTEREST = 'GET_INTEREST';
export const UPDATE_INTEREST = 'UPDATE_INTEREST';
export const ADD_INTEREST = 'ADD_INTEREST';
export const INTEREST_ERROR = 'INTEREST_ERROR';

// upload Pdf
export const GET_UPLOAD_PDF = 'GET_UPLOAD_PDF';
export const UPLOAD_PDF = 'UPLOAD_PDF';
export const UPDATE_UPLOAD_PDF = 'UPDATE_UPLOAD_PDF';
export const UPLOAD_PDF_ERROR = 'UPLOAD_PDF_ERROR';

// GET ALL BOOKS

export const GET_ALL_BOOK = 'GET_ALL_BOOK';
export const UPLOAD_ALL_BOOK = 'UPLOAD_ALL_BOOK';
export const UPDATE__ALL_BOOK = 'UPDATE__ALL_BOOK';
export const ERROR_ALL_BOOK = 'ERROR_ALL_BOOK';

// SUGGESTED NOTE/BOOKS

export const GET_SUGGESTED_BOOK = 'GET_SUGGESTED_BOOK';
export const UPLOAD_SUGGESTED_BOOK = 'UPLOAD_SUGGESTED_BOOK';
export const UPDATE_SUGGESTED_BOOK = 'UPDATE_SUGGESTED_BOOK';
export const ERROR_SUGGESTED_BOOK = 'ERROR_SUGGESTED_BOOK';

// SINGLE NOTE/BOOKS

export const GET_SINGLE_BOOK = 'GET_SINGLE_BOOK';
export const ERROR_SINGLE_BOOK = 'ERROR_SINGLE_BOOK';

// POPULAR BOOK

export const GET_POPULAR_BOOK = 'GET_POPULAR_BOOK';
export const UPLOAD_POPULAR_BOOK = 'UPLOAD_POPULAR_BOOK';
export const UPDATE_POPULAR_BOOK = 'UPDATE_POPULAR_BOOK';
export const ERROR_POPULAR_BOOK = 'ERROR_POPULAR_BOOK';

// FOLLOW
export const FOLLOW_USER_LOADING = 'FOLLOW_USER_LOADING ';
export const GET_FOLLOW_USER = 'GET_FOLLOW_USER';
export const FOLLOW_USER = 'FOLLOW_USER';
export const ERROR_FOLLOW_USER = 'ERROR_FOLLOW_USER';

export const UN_FOLLOW_USER_LOADING = 'UN_FOLLOW_USER_LOADING ';
export const UN_ERROR_FOLLOW_USER = 'UN_ERROR_FOLLOW_USER';


// Library
export const NEW_LIBRARY_BOOK = 'NEW_LIBRARY_BOOK';
export const FINISHED_LIBRARY_BOOK = 'FINISHED_LIBRARY_BOOK';
export const ERROR_FINISHED_LIBRARY_BOOK = 'ERROR_FINISHED_LIBRARY_BOOK';
// export const NEW_LIBRARY_BOOK = 'NEW_LIBRARY_BOOK';
export const ERROR_LIBRARY_BOOK = 'ERROR_LIBRARY_BOOK';

export const GET_FINISHED_LIBRARY_BOOK = 'GET_FINISHED_LIBRARY_BOOK';
export const POST_FINISHED_LIBRARY_BOOK = 'POST_FINISHED_LIBRARY_BOOK';
// export const NEW_LIBRARY_BOOK = 'NEW_LIBRARY_BOOK';
export const ERROR_GET_FINISHED_LIBRARY_BOOK =
  'ERROR_GET_FINISHED_LIBRARY_BOOK';

export const GET_READING_LIBRARY_BOOK = 'GET_READING_LIBRARY_BOOK';
export const POST_READING_LIBRARY_BOOK = 'POST_READING_LIBRARY_BOOK';
export const ERROR_READING_FINISHED_LIBRARY_BOOK =
  'ERROR_READING_FINISHED_LIBRARY_BOOK';

// COMMENTS
export const GET_COMMENTS_BOOK = 'GET_COMMENTS_BOOK';
export const UPLOAD_COMMENTS_BOOK = 'UPLOAD_COMMENTS_BOOK';
export const UPDATE_COMMENTS_BOOK = 'UPDATE_COMMENTS_BOOK';
export const ERROR_COMMENTS_BOOK = 'ERROR_COMMENTS_BOOK';

export const REPLY_COMMENTS = 'REPLY_COMMENTS';
export const ERROR_REPLY_BOOK = 'ERROR_REPLY_BOOK';

// RATING
export const GET_RATING_BOOK = 'GET_RATING_BOOK';
export const POST_RATING_BOOK = 'POST_RATING_BOOK';
export const UPDATE_RATING_BOOK = 'UPDATE_RATING_BOOK';
export const ERROR_RATING_BOOK = 'ERROR_RATING_BOOK';

// RATING
export const GET_VOICE_RECOREDED = 'GET_VOICE_RECOREDED';
export const POST_VOICE_RECOREDED = 'POST_VOICE_RECOREDED';
export const UPDATE_VOICE_RECOREDED = 'UPDATE_VOICE_RECOREDED';
export const ERROR_VOICE_RECOREDED = 'ERROR_VOICE_RECOREDED';

//SUBSCRIPTION
export const GET_SUBSCRIPTION_PAYMENT = 'GET_SUBSCRIPTION_PAYMENT';
export const POST_SUBSCRIPTION_PAYMENT = 'POST_SUBSCRIPTION_PAYMENT';
export const UPDATE_SUBSCRIPTION_PAYMENT = 'UPDATE_SUBSCRIPTION_PAYMENT';
export const ERROR_SUBSCRIPTION_PAYMENT = 'ERROR_SUBSCRIPTION_PAYMENT';
export const ERROR_POST_SUBSCRIPTION_PAYMENT =
  'ERROR_POST_SUBSCRIPTION_PAYMENT';
